== Accessible authoring tools for Education ==

This page gets you started in understanding some key points, as well as explanation of terminology and links to practical resources for accessible education.

[@@ Related Video on authoring tools?] Authoring Tools Accessibility Overview

=== Introduction: Accessible tools in education: ===

In your school or university, using tools that support both the creation of accessible content for your students, and being accessible itself, is the goal. Accessible tools are more inclusive and can greatly improve the efficiency of teachers and students.

Where a teacher or lecturer has little knowledge of accessibility, a good tool can also assist you to produce accessible content by making suggestions that are appropriate at different stages in the writing or content creation process. This applies equally to creating PDF documents or videos.

The accessibility of your content has an impact on the quality of your teaching and learning activities, to create a level playing field and remove barriers for teachers and students with disabilities alike.

 
=== How using accessible authoring tools helps === 

Using the right tool can reduce 'extra' work needed to reach your accessibility goals, reduce the need to retrofit content for accessibility, and unnecessarily duplicate your workload by creating content first time round that meets diverse user needs.

Understand the process for accessible authoring is also important, there may be 'many steps' in the process. For example, consider a simple webpage or downloadable document that you wish to deliver to your students. You may need to undertake the following:

* Simple color contrast checking, can make all the different between being able to perceive and understand critical content for a people with a vision impairment. 

* If you have PDFs, or Word documents, you need to make them accessible at source too. No tool will automatically make this happen, but with some simple steps you can use existing features of Word or Acrobat to make your documents highly accessible with not much effort. This can make your resources accessible to users of assistive technology, such as screen reader users and others.

* If you are adding video or other and rich media, many tools allow you to caption your content, add text-transcriptions. If you are linking to these resources, then please check that they also have captions.

* If using interactive storyboards or games in your education resources, these tools should have features that provide alternatives than can be perceived to users who are non-sighted or deaf and hard of hearing.

There are many things to consider - and a good, accessible authoring tool, should help with this process. Combined with some sound basic knowledge of accessibility, you will be well on your way to creating more accessible experiences for your students.


=== Getting the right accessible tools === 

Procurers of technology for use in education and the workplace have a responsibility to choose tools that support people with disabilities, so the tool is not itself a barrier and is usable by the broadest audience.

Ensure when choosing new tools you ask your vendor about accessibility, check any  Voluntary Product Accessibility Template (VPAT)/Accessibility Conformance Report (ACR) to be happily the tool will meet your needs. 

Getting this right can be tricky, as it needs buy-in from management, to make accessibility a core requirement of the tools you use on campus. This can be made easier by making sure you only use tools that support accessibility in your school or university. 

This is not as difficult as it sounds! Many off the shelf content management systems have WYSIWYG that support accessibility, or programs you use to create offline documents also have tools that support accessibility. Sometimes it is just a matter of knowing where to look.

You may even already be making documents more accessible, but not even know it. Chances are, you are already making content accessible in your Word documents by using document styles! For more, see [# Create accessible Word documents.]


=== Practical things you can do ===

* Introduce a process for the creation of accessible documents and content.
* Use an LMS that supports accessibility.
* Use a CMS that is accessible to people with disabilities.
* Create accessible Word documents.
* Create accessible PDF documents.
* Create accessible PowerPoint presentations.
* Create accessible videos.
* Use built in accessibility checkers.

=== More Information and Guidance ===


* [https://www.w3.org/WAI/standards-guidelines/wcag/glance/ WCAG at a glance] This give a simple helpful summary of WCAG 2.1 in a way that is easy to digest.
* [https://www.w3.org/WAI/WCAG21/quickref/  How to Meet WCAG (Quick Reference)] - A customizable quick reference to Web Content Accessibility Guidelines (WCAG) 2 requirements (success criteria) and techniques 
* [https://www.w3.org/WAI/standards-guidelines/wcag/faq/ WCAG FAQ
* [https://www.w3.org/WAI/fundamentals/accessibility-principles/ Accessibility Principles]
* [https://www.w3.org/WAI/perspective-videos/ Web Accessibility Perspectives Videos: Explore the Impact and Benefits for Everyone]
* [https://www.w3.org/WAI/people-use-web/ How People with Disabilities Use the Web]
* Want a clear, simple intro to help you understand some key points you need to look for when choosing an accessible authoring tool? Try[https://www.w3.org/WAI/standards-guidelines/atag/glance/ ATAG at a glance]
* [https://www.w3.org/WAI/fundamentals/foundations-course/ Want to learn more? Take the Digital Accessibility Foundations Free Online Course]
* [https://www.w3.org/WAI/news/2019-12-03/new-online-course-w3cx-introduction-to-web-accessibility/ New Online Course: W3Cx Introduction to Web Accessibility]

=== Terminology === 
 
 @@