== Overview ==

The majority of digital content is generated using authoring tools, but those who generate this content don't think they are using an 'authoring tool'. Ordinary people just don't think in these terms. Whether they use a content management system (CMS), code, video or graphics editors -  these tools have a primary role in guiding and supporting users in creating accessible content.

Using a tool that supports the creation of accessible content, as well as being accessible itself, is the sweet spot we want to hit. These tools are, by nature, more inclusive and can greatly improve the efficiency of designers, developers, and content authors in employment, education and other contexts.

Where a content author has little knowledge of accessibility, a good tool can also assist the author, and provide them with the ques and support they need to produce accessible content. Procurers of technology for use in education and the workplace have a responsibility to choose tools that support people with disabilities, so the tool is not itself a barrier and is usable.

=== Outreach Goals ===

We aim to create resources to raise awareness of the benefits of accessible authoring tools. The objective of these resources is to target various sectors with informational briefs that are designed to both illustrate the importance and power of authoring tools for accessibility. This is both for the user of these tools and for their ability to create accessible content.

At a high level, the proposed target audience (for each sector) is generally two types:

* Management / Decision Makers
* Technical people / Content creators

To support these goals, we aim to create 'briefs' for various industry sectors that are suggested below. 

=== Overview of briefs ===

These will include:

* Short written briefs that highlight the benefits of accessible authoring tools. Each brief will be a single page with several related sections (similar to https://www.w3.org/WAI/planning/involving-users/ [Involving Users in Web Projects for Better, Easier Accessibility])
* Tone (@@ I'm not sure how to express what the tone should be - friendly, informative, informal??)
* These will be for web only (@@ Shadi is this ok? Or do you want to include print?)
* Potentially the creation of graphics for dissemination that are thought-provoking/useful. These could be downloaded from GitHub for distribution and printing.

Feedback is welcome on the suitability of the target audience options, as well as the messaging.

=== Note on general takeaways we want to get across ===

There are some common takeaways that we would like to make that can be either added to each of the sectors: These may include:

* Procure accessible only.
* The tools you choose impact how accessible your content is.
* Choose an authoring tool with an accessible user interface.
* Choose an authoring tool that produces accessible content.
* Promote learn about simple, non-technical thing's user can do to create accessible content with authoring - this could be structuring content using headings, clear descriptive link text etc.
* Promote positive engagement with vendors to ask for more or improved accessibility if not satisfied.
* Raise awareness of ATAG.
* Encourage procurers to check the documentation of the system they aim to use to ensure it supports accessibility, and that this can be measure using ATAG.
* Do not disable accessibility related features in tooling.
* When building industry-specific tools, ensure accessibility is supported by the content creation aspects of the tool.
* When building industry-specific tools, make sure each sector develops according to ATAG.

=== Outreach to specific audience sectors & options ===

The following are some suggested topics for the briefs described above, from which we propose to select 3 topics to develop into final briefs. Please review and let us know if there are preferences, gaps or omissions. 

== Option 1: Publishing - e-books ==
=== Audience: Product Owners, Content Designers, Writers, Designers Producers, 3-party services, etc. ===
==== Key Messages ====
* Digital publishing tools need to be accessible to everyone, including staff with disabilities.

* Q: I'm not sure what the focus should be here? Are we saying the tools to create e-books themselves need to be covered in this project? To what degree do we need to cover e-book accessibility itself?

@@ Josh to arrange calls and get input from domain experts

== Option 2: Publishing - web ==
=== Audience: Product Owners, Content Designers, Writers, Designers Producers, 3-party services, etc. ===
==== Key Messages ====
* Digital publishing tools need to be accessible to everyone, including staff with disabilities working in getting content online.
* These include CMS, blogging tools, wikis, video creation tools, graphics tools, presentation tools.

== Option 3: Education ==
=== Audience: Teachers, education IT departments, 3-party services, etc. ===
==== Key Messages ====
* Learning management systems need to be accessible to everyone, including students as well as teachers with disabilities.
* Bespoke systems need to be designed with accessibility in mind and support the creation of accessible content.
* Your courses need to be accessible to students with disabilities
* Your platforms need to be usable by teachers with disabilities
* Chose the correct accessible learning management system
* CMS, blogging tools, wikis. Video creation tools, graphics tools. Presentation tools.

@@ Josh to arrange calls and get input from lecturers etc

== Option 4:  Social Media ==
=== Audience: End-Users, e.g. marketing departments, influencers, product owners, innovation managers, etc. ===
==== Key Messages ====
* Your postings may not be accessible to everyone
* Most platforms provide accessibility features that are easy to use - should we provide examples?
* Social media postings need to be accessible for everyone
* Many social media platforms provide accessibility features
* You also need to provide features if you want to be relevant
* Your platform can be more inclusive by being more accessible

== Option 5: Healthcare ==
=== Audience: Developers, esp. IT departments, 3-party services, etc. ===
==== Key Messages ====
* HR / CRM systems need to be accessible to everyone
* This includes doctors and nurses as well as patients with disabilities
* Formats that people receive any online prescriptions or healthcare advice need to be accessible, and accessible authoring tools can help with that.

@@ Josh knows little about this space and not sure who to talk to 
